{% set name = "pooch" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ec3fa446f0f5ff45e7283f13040cd1caf6857a2327b004e542a2df8af0c45a0

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
  host:
    - python
    - pip
  run:
    - python
    - requests
    - packaging
    - backports.tempfile  # [py2k]
    - pathlib  # [py2k]

test:
  requires:
    - pytest
  imports:
    - pooch
  commands:
    - pytest --pyargs pooch.tests.test_integration

about:
  home: http://github.com/fatiando/pooch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "A friend to fetch your Python library's sample data files"
  description: |
    Pooch will manage downloading your sample data files over HTTP from a server and
    storing them in a local directory. (1) Download a file only if it's not in the local
    storage. (2) Check the SHA256 hash to make sure the file is not corrupted or needs
    updating. (3) If the hash is different from the registry, Pooch will download a new
    version of the file. (4) If the hash still doesn't match, Pooch will raise an
    exception warning of possible data corruption.
  doc_url: http://www.fatiando.org/pooch
  dev_url: http://github.com/fatiando/pooch

extra:
  recipe-maintainers:
    - leouieda
    - dopplershift
