{% set name = "pooch" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57d20ec4b10dd694d2b05bb64bc6b109c6e85a6c1405794ce87ed8b341ab3f44

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - requests
    - packaging
    - appdirs

test:
  requires:
    - pytest
  imports:
    - pooch
  commands:
    - pytest --pyargs pooch.tests.test_integration

about:
  home: https://github.com/fatiando/pooch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A friend to fetch your data files
  description: |
    Pooch manages your remote data files. It automatically downloads and stores
    them in a local directory (using HTTP or FTP), with support for versioning,
    corruption checks, and custom download and post-processing operations.
  doc_url: https://www.fatiando.org/pooch
  dev_url: https://github.com/fatiando/pooch

extra:
  recipe-maintainers:
    - leouieda
    - dopplershift
