{% set name = "pooch" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0142b80b61fce06a9837c7040f79ffc2a94c271422460b86e73fee94f0a57e2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
  host:
    - python
    - pip
  run:
    - python
    - requests
    - packaging
    - appdirs
    - backports.tempfile  # [py2k]
    - pathlib  # [py2k]

test:
  requires:
    - pytest
  imports:
    - pooch
  commands:
    - pytest --pyargs pooch.tests.test_integration

about:
  home: https://github.com/fatiando/pooch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "A friend to fetch your Python library's sample data files"
  description: |
    Pooch will manage downloading your sample data files over HTTP from a server and
    storing them in a local directory. (1) Download a file only if it's not in the local
    storage. (2) Check the SHA256 hash to make sure the file is not corrupted or needs
    updating. (3) If the hash is different from the registry, Pooch will download a new
    version of the file. (4) If the hash still doesn't match, Pooch will raise an
    exception warning of possible data corruption.
  doc_url: https://www.fatiando.org/pooch
  dev_url: https://github.com/fatiando/pooch

extra:
  recipe-maintainers:
    - leouieda
    - dopplershift
