{% set name = "pooch" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27ef63097dd9a6e4f9d2694f5cfbf2f0a5defa44fccafec08d601e731d746270

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps -vv

    requirements:
      host:
        - python >=3.7
        - pip
        - setuptools_scm >=6.2
      run:
        - python >=3.7
        - platformdirs >=2.5.0
        - packaging >=20.0
        - requests >=2.19.0

    test:
      requires:
        - pytest
      imports:
        - pooch
      commands:
        - pytest --pyargs pooch.tests.test_integration

  - name: {{ name }}-extra
    version: {{ version }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps -vv

    requirements:
      host:
        - python >=3.7
        - pip
        - setuptools_scm >=6.2
      run:
        - {{ pin_subpackage(name) }}
        - tqdm >=4.41.0,<5.0.0
        - python-xxhash >=1.4.3
        - paramiko >=2.7.0

    test:
      requires:
        - pytest
      imports:
        - pooch
        - xxhash
        - tqdm
        - paramiko
      commands:
        - pytest --pyargs pooch.tests.test_integration

about:
  home: https://github.com/fatiando/pooch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A friend to fetch your data files
  description: |
    Pooch manages your remote data files. It automatically downloads and stores
    them in a local directory (using HTTP or FTP), with support for versioning,
    corruption checks, and custom download and post-processing operations.
  doc_url: https://www.fatiando.org/pooch
  dev_url: https://github.com/fatiando/pooch

extra:
  recipe-maintainers:
    - leouieda
    - dopplershift
