travis:
  secure:
    BINSTAR_TOKEN: QTiTC2TY1CjE0Jey8WHjnFIV98sQSvdfZEOXzIrLFU9G2ESl6OLByyrvFi3qRdeuhW3iQUThBl6VeeWEZHlXWKNJOuHhMTfNJw2hYIfLnUie1RO2asKXn0m0AHLP7l8AL2zmW5QPHghDTzY4ry/WUVyuUNbYWpVLeS7/5ffkXKrIrgOPMmzssIsIj48B7bQfreN4xF+pEawumuLhdgSi84YKE7De1b7KsIAnqSOeicYpPjcaWzajMPzxwpPz0OAcY8vspLDhEHKJZUBGzkHvGvj+kg1gXtacgS/3D6nUD8joUcv+JpozQS7SXJfhcwqK6k/XVaj1HLKVWVvHPt4A8063U8oRZomAB6UGoUhQ1SyiTEl6XAOHHDn192Oe6aE2nb8CuIEMDK+hbgF6nskdC6bQBMDWVITMr8Q7XHFnedW8YW/ZC6ejR2onzKNkBxe/nXH8kEXxe5ef4YqioMjIGEeEuwmoZvqlk14FQuD0br6Bmh9tkYsRRn7lwgkwc1hd/nHAEhr3UUSJeAI8q05dmxUa/s3+c7t9tzp+zL6CG5pcnABkx1F+jgjDXZFa1U7ZwnR+wNlZp02b/RvtTYvxWTSx/+Qn6rier7tuMOvie71RABnry1fMZnlfs9fbqnmrygEVwWvQw/4jOQkV4J4FSKnuMER0MeUuABSLsj8fUus=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
